### ISSUE TITLE
[F] Display current data in GUI

### ISSUE THREAD

**Issue by lubiedak** [PawelSzczygielski/RepositoryGroomer#6]
After discussion with Speed, we decided to use ReactiveUI as MVVM framework + WPF as display layer.

**Comment by PawelSzczygielski** [comment]
After discussion with Speed, we decided to use ReactiveUI as MVVM framework + WPF as display layer.

**Comment by PawelSzczygielski** [comment]
The WPF + Caliburn.Micro is used as simpler solution better suited for such small project.
